### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by anthonybrown** [jsumners/alfred-emoji#26]
Not sure if I'm installing this correctly but I cloned the repo and did `npm install` then `npm run build`
This is where I'm getting the error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.6.0 build: `./build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2018-04-18T17_41_12_062Z-debug.log
```

**Comment by jsumners** [comment]
What happens if you run `bulid.sh` directly?

**Comment by anthonybrown** [comment]
with `npx build.sh` ?

**Comment by jsumners** [comment]
I don't know anything about Homebrew. But `npx build.sh` is incorrect. It's just a Bash shell script: `./build.sh`.

**Comment by anthonybrown** [comment]
yep, I got the error above

**Comment by jsumners** [comment]
It's running fine over here. Do:

```sh
$ set -x
$ ./build.sh
```

Then paste the output here.

**Comment by anthonybrown** [comment]
I recloned the repo and ran `npm i` then `./build.sh`
working now.

Thanks!

**Comment by jsumners** [comment]
Glad you got it working. Enjoy! 😀

**Comment by anthonybrown** [comment]
spoke too soon, I'm getting another error while running `npm run load`
```
Updating version ...
Injecting readme ...
Injecting auto-update script ...
Bundling workflow ...
No application knows how to open /Users/tony/.Trash/alfred-emoji/alfred-emoji.alfredworkflow.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.6.0 load: `npm run build && open alfred-emoji.alfredworkflow`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.6.0 load script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2018-04-19T13_47_24_467Z-debug.log
```

**Comment by anthonybrown** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'load' ]
2 info using npm@5.8.0
3 info using node@v9.11.1
4 verbose run-script [ 'preload', 'load', 'postload' ]
5 info lifecycle @1.6.0~preload: @1.6.0
6 info lifecycle @1.6.0~load: @1.6.0
7 verbose lifecycle @1.6.0~load: unsafe-perm in lifecycle true
8 verbose lifecycle @1.6.0~load: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/tony/.Trash/alfred-emoji/node_modules/.bin:/usr/local/sbin:/Users/tony/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go/libexec/bin
9 verbose lifecycle @1.6.0~load: CWD: /Users/tony/.Trash/alfred-emoji
10 silly lifecycle @1.6.0~load: Args: [ '-c', 'npm run build && open alfred-emoji.alfredworkflow' ]
11 silly lifecycle @1.6.0~load: Returned: code: 1  signal: null
12 info lifecycle @1.6.0~load: Failed to exec load script
13 verbose stack Error: @1.6.0 load: `npm run build && open alfred-emoji.alfredworkflow`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid @1.6.0
15 verbose cwd /Users/tony/.Trash/alfred-emoji
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/Cellar/node/9.11.1/bin/node" "/usr/local/bin/npm" "run" "load"
18 verbose node v9.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error @1.6.0 load: `npm run build && open alfred-emoji.alfredworkflow`
22 error Exit status 1
23 error Failed at the @1.6.0 load script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jsumners** [comment]
Do you have Alfred installed? alfredapp.com

**Comment by anthonybrown** [comment]
yes

**Comment by anthonybrown** [comment]
looks like it built this time, I did the `set -x` and ran the `./build.sh` then did `npm run load`
no errors but how do this work now?

**Comment by jsumners** [comment]
I don't have an answer for you. `open` is a standard macOS utility that opens files with their associated application. Alfred should be registered to handle `.alfredworkflow` files.

**Comment by anthonybrown** [comment]
ok, seems like it's my terminal is hanging from the last command

**Comment by anthonybrown** [comment]
![screen shot 2018-04-19 at 10 11 21 am](https://user-images.githubusercontent.com/1719818/38996834-09d6da8a-43ba-11e8-98c2-dab0ccce2e2f.png)

**Comment by anthonybrown** [comment]
are you running `High Sierra`?

**Comment by jsumners** [comment]
Yes.

**Comment by anthonybrown** [comment]
I had an old copy of Alfred, installed Alfred 3 and bought the powerpack, works fine now.
Maybe you should include a more detailed `README.md`?
